DROP TABLE IF EXISTS puzzle;

CREATE TABLE puzzle (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  question TEXT UNIQUE NOT NULL,
  token TEXT,
  x0 INTEGER,
  y0 INTEGER,
  x1 INTEGER,
  y1 INTEGER,
  x2 INTEGER,
  y2 INTEGER,
  typ TEXT NOT NULL
);